### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by bo-wu** [taochenshh/exp4nav#1]
Hello author,

I am very interested in your work, and try to run the code. However, I run into the error as follows:

```
Traceback (most recent call last):
  File "test_policy.py", line 118, in <module>
    main()
  File "test_policy.py", line 93, in main
    cum_area, cum_reward, cum_actions = agent.test(render=args.render, val_id=0)
  File "/home/dell/explore/exp4nav/src/algos/ppo_map.py", line 136, in test
    obs_uint8 = self.env.reset([self.house_config['fixed_test_set'][val_id]])
  File "/home/dell/explore/exp4nav/src/utils/subproc_vec_env.py", line 76, in reset
    obs = [remote.recv() for remote in self.remotes]
  File "/home/dell/explore/exp4nav/src/utils/subproc_vec_env.py", line 76, in <listcomp>
    obs = [remote.recv() for remote in self.remotes]
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

```

I am using Python 3.5.2 (default Python3 version for Ubuntu 16.04). Have you ever met such issue?

**Comment by taochenshh** [comment]
Did you get such error when you trained the network? Does this only happen when you run `test_policy.py`?

**Comment by taochenshh** [comment]
Also, can you show the complete error in your terminal?

**Comment by bo-wu** [comment]
It happened both, i.e. I got same error when trained the network. 
That's already complete error info in the terminal. I show you the error for training now.

```
critic_fc.0.weight True
critic_fc.0.bias True
critic_head.weight True
critic_head.bias True
=================================
 Checkpoint loaded...
           ../pretrain/il_map_rgb/model/model_best.pth
creating house d800d4dc09e45f408f7f37802dfda765 ...
creating house 1e6902285d93d085bcee81befff27044 ...
creating house 75a0d79f6c9b3d5ce058f218b30a35de ...
creating house 0f93cf8b5f6375521bfb84bf8a6f86b8 ...
creating house 8356de0efb8a5f994210e0318c21d977 ...
creating house e813a59797612b21448108f1d7023a39 ...
creating house e12192d1e4a602a2e63d04b92f3cd7b3 ...
creating house 78cbb14b35d75bff69d672df957dd190 ...
Traceback (most recent call last):
  File "main.py", line 92, in <module>
    main()
  File "main.py", line 87, in main
    agent.train()
  File "/home/dell/explore/exp4nav/src/algos/ppo_map.py", line 46, in train
    res = self.rollout(val=True)
  File "/home/dell/explore/exp4nav/src/algos/ppo_map.py", line 267, in rollout
    obs_uint8 = env.reset(self.house_config['fixed_val_set'])
  File "/home/dell/explore/exp4nav/src/utils/subproc_vec_env.py", line 76, in reset
    obs = [remote.recv() for remote in self.remotes]
  File "/home/dell/explore/exp4nav/src/utils/subproc_vec_env.py", line 76, in <listcomp>
    obs = [remote.recv() for remote in self.remotes]
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```
the command is similar as the one you provided, except end with --render_door
`
python main.py --lr=0.00001 --rnn_hidden_dim=128 --area_reward_scale=0.0005 --gamma=0.999        --collision_penalty=0.006 --ent_coef=0.01  --train_rollout_repeat=2 --max_depth=3        --num_steps=500 --il_pretrain --pretrain_dir=../pretrain/il_map_rgb/model         --num_envs=8 --use_rgb_with_map   --save_dir=data/map_rgb --seed=1 --render_door
`

**Comment by taochenshh** [comment]
I cannot reproduce your error. Does the code work if u don't add `--render_door`

**Comment by bo-wu** [comment]
That's weird. I got same error even without `--render_door`
Maybe I should try Python 3.6

**Comment by bo-wu** [comment]
I tried Python3.6 but still got same error.
Not sure where the problem is.

**Comment by taochenshh** [comment]
It's very likely that there are some setup steps missing. Could you please set a breakpoint in `reset()` function in `house3dRGBD.py`, and see which line gives the error? To make the debugging easier, you may set the `--num_envs=1`

**Comment by bo-wu** [comment]
Maybe because I installed some packages which are not same version as that in environment.yml.
Now I can run your code. Thanks

**Comment by SHYang1210** [comment]
Hello, can you provide the SUNCG data set and the SUNCGtoolbox, and the provided links are no longer valid. Thank you very much
